concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker-runner"
  url = "https://gitlab.yfpo.com"
  id = 1
  token = "_5Lwjzkrz4Ywme5y--kp"
  token_obtained_at = 2026-01-29T07:42:40Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  tags = ["docker", "linux"]
  run_untagged = true
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "docker.1ms.run/library/alpine:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    shm_size = 0
    extra_hosts = ["gitlab.yfpo.com:10.252.4.135"]